import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/layouts/Header";
import Footer from "../components/layouts/Footer";

import JumbotronLayout from "../assets/img/Group3761.svg";
import JumbotronLoc from "../assets/img/location.svg";
import BlueBanner from "../assets/img/BlueBanner.svg";
import BannerVector from "../assets/img/Vector.svg";
import Benefit1 from "../assets/img/Work1.svg";
import BenefitBix from "../assets/img/benefit/01/Rectangle71.svg";
import BenefitOnline from "../assets/img/benefit/01/Outline.svg";
import BenefitPencarian from "../assets/img/benefit/02/Vector.svg";
import BenefitTarif from "../assets/img/benefit/03/Vector.svg";
import BenefitFleksibel from "../assets/img/benefit/04/Vector.svg";
import No1 from "../assets/img/no1.svg";
import No2 from "../assets/img/no2.svg";
import No3 from "../assets/img/no3.svg";
import KursusDesain from "../assets/img/Group3748.svg";
import GuruBenefit from "../assets/img/GuruBenefit.svg";
import MuridBenefit from "../assets/img/MuridBenefit.svg";
import Previous from "../assets/img/Previous.svg";
import Next from "../assets/img/Next.svg";
import SubjekThumbnail from "../assets/img/subjek-thumbnail.svg";
import Favorite from "../assets/img/Fav.svg";
import Verify from "../assets/img/Verify.svg";
import Star from "../assets/img/Star.svg";
import Divider from "../assets/img/Line8.svg";
import GOR from "../assets/img/GroupOfReviewer.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Troffen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id="jumbotron">
        <div className={styles.jumbotron_content} style={{ backgroundImage: `url(${JumbotronLayout.src})` }}>
          <div className={styles.container}>
            <div className={styles.content}>
              <div className={styles.content1}>Temukan dan belajar dari guru yang sesuai kriteriamu.</div>
              <div className={styles.content2}>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.</div>
              <div className={styles.content3}>
                <div className={styles.search_subject}>
                  <input type="text" placeholder="Mau belajar apa hari ini?" />
                </div>
                <div className={styles.search_location}>
                  <Image src={JumbotronLoc} priority />
                  {/* <img src="/assets/Troffen - MVP/location.svg" alt="an image" /> */}
                  <input type="text" placeholder="Lokasi" />
                  <button className={styles.button_search}>Cari Kursus</button>
                </div>
              </div>
              <div className={styles.content4}>
                Belum tahu tentang Troffen <a href="#">Pelajari di sini</a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="banner-1">
        <div className={styles.banner1} style={{ backgroundImage: `url(${BlueBanner.src})` }}>
          <div className={styles.banner1_label}>
            <div className={styles.banner1_label1}>
              <Image src={BannerVector} priority />
              {/* <img src="/assets/Troffen - MVP/Vector.svg" alt="an image" /> */}
              <nav>50+ Subject Kursus</nav>
            </div>
            <div className={styles.banner1_label2}>
              <Image src={BannerVector} priority />
              {/* <img src="/assets/Troffen - MVP/Vector.svg" alt="an image" /> */}
              <nav>Kursus Online & Offline</nav>
            </div>
            <div className={styles.banner1_label3}>
              <Image src={BannerVector} priority />
              {/* <img src="/assets/Troffen - MVP/Vector.svg" alt="an image" /> */}
              <nav>Tutor Terpercaya</nav>
            </div>
          </div>
        </div>
      </section>

      <section id="benefit">
        <div className={styles.container}>
          <div className={styles.benefit}>
            <div className={styles.benefit_title}>Kursus Online Kini Lebih Menyenangkan</div>
            <div className={styles.benefit_content}>
              <div className={styles.benefit_content_left}>
                <Image src={Benefit1} priority />
                {/* <img src="/assets//Troffen - MVP/Work1.svg" alt="an image" /> */}
              </div>
              <div className={styles.benefit_content_right}>
                <div className={styles.benefit_content_container}>
                  <div className={styles.benefit1}>
                    <div className={styles.image}>
                      <Image src={BenefitBix} priority className={styles.image_1} />
                      <Image src={BenefitOnline} priority className={styles.image_2} />
                    </div>
                    <div className={styles.title}>Online & Offline</div>
                    <div className={styles.text}>Kursus tersedia secara online dan offline sesuai domisili kamu.</div>
                  </div>
                  <div className={styles.benefit2}>
                    <div className={styles.image}>
                      <Image src={BenefitBix} priority className={styles.image_1} />
                      <Image src={BenefitPencarian} priority className={styles.image_2} />
                    </div>
                    <div className={styles.title}>Pencarian Cepat</div>
                    <div className={styles.text}>Cukup ketik subjek kursus yang kamu inginkan, guru idaman akan muncul!</div>
                  </div>
                  <div className={styles.benefit3}>
                    <div className={styles.image}>
                      <Image src={BenefitBix} priority className={styles.image_1} />
                      <Image src={BenefitTarif} priority className={styles.image_2} />
                    </div>
                    <div className={styles.title}>Tarif Sesuai Preferensi</div>
                    <div className={styles.text}>Pilih guru dengan tarif yang fleksibel sesuai dengan preferensimu.</div>
                  </div>
                  <div className={styles.benefit4}>
                    <div className={styles.image}>
                      <Image src={BenefitBix} priority className={styles.image_1} />
                      <Image src={BenefitFleksibel} priority className={styles.image_2} />
                    </div>
                    <div className={styles.title}>Jam Kursus Fleksibel</div>
                    <div className={styles.text}>Atur jam kursus langsung dengan guru tanpa batasan apapun.</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="kursus">
        <div className={styles.container}>
          <div className={styles.kursus}>
            <div className={styles.kursus_title}>
              <div className={styles.kursus_title_1}>Langkah Mudah Menemukan Kursus</div>
              <div className={styles.kursus_title_2}>Cukup 3 langkah untuk mendapatkan guru sesuai kriteria yang kamu inginkan!</div>
            </div>
            <div className={styles.kursus_box}>
              <div className={styles.kursus_box_left}>
                <div className={styles.kursus_box_1_left}>
                  <div className={styles.kursus_box_1_left_1}>
                    <div className={styles.kursus_box_1_left_1_title}>
                      <Image src={No1} priority />
                      {/* <img src="/assets//Troffen - MVP/no1.svg" alt="an image" /> */}
                      <nav>Temukan Guru</nav>
                    </div>
                    <div className={styles.kursus_box_1_left_1_desc}>Cek profil guru dengan bebas dan pilih guru yang kamu inginkan sesuai dengan kebutuhan dan kriteria.</div>
                  </div>
                </div>
                <div className={styles.kursus_box_2_left}>
                  <div className={styles.kursus_box_2_left_1}>
                    <div className={styles.kursus_box_2_left_1_title}>
                      <Image src={No2} priority />
                      {/* <img src="/assets//Troffen - MVP/no2.svg" alt="an image" /> */}
                      <nav>Permintaan Kursus</nav>
                    </div>
                    <div className={styles.kursus_box_2_left_1_desc}>Para guru akan memberikan tanggapan terhadap permintaan kursus kamu dalam beberapa jam!</div>
                  </div>
                </div>
                <div className={styles.kursus_box_3_left}>
                  <div className={styles.kursus_box_3_left_1}>
                    <div className={styles.kursus_box_3_left_1_title}>
                      <Image src={No3} priority />
                      {/* <img src="/assets//Troffen - MVP/no3.svg" alt="an image" /> */}
                      <nav>Atur Jadwal Kursus</nav>
                    </div>
                    <div className={styles.kursus_box_3_left_1_desc}>Atur jadwal kursus Kamu sendiri dengan kursus dan guru yang dipilih.</div>
                  </div>
                </div>
              </div>
              <div className={styles.kursus_box_right}>
                <Image src={KursusDesain} priority />
                {/* <img src="/assets/Troffen - MVP/Group3748.svg" alt="an image" /> */}
                <nav className={styles.kursus_desain}>KURSUS DESAIN</nav>
                <nav className={styles.guru_tersedia}>200 GURU TERSEDIA</nav>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="subjek">
        <div className={styles.container}>
          <div className={styles.subjek}>
            <div className={styles.subjek_title}>
              <div className={styles.subjek_title_main}>Temukan subjek dan guru yang sesuai</div>
              <div className={styles.subjek_title_action}>
                <div className={styles.previous}>
                  <Image src={Previous} priority />
                  {/* <img src="/assets/Troffen - MVP/Previous.svg" alt="an image" /> */}
                </div>
                <div className={styles.next}>
                  <Image src={Next} priority />
                  {/* <img src="/assets/Troffen - MVP/Next.svg" alt="an image" /> */}
                </div>
              </div>
            </div>
            <div className={styles.subjek_gallery}>
              {[0, 1].map(() => (
                <div className={styles.subjek_gallery_row}>
                  <div className={styles.subjek_gallery_card}>
                    <div className={styles.subjek_thumbnail}>
                      <Image src={SubjekThumbnail} priority />
                      {/* <img src="/assets/Troffen - MVP/subjek-thumbnail.svg" alt="an image" /> */}
                    </div>
                    <div className={styles.subjek_content}>
                      <div className={styles.subjek_content_title}>
                        <div className={styles.subjek_content_title_main}>Basic UI/UX Design</div>
                        <div className={styles.subjek_content_title_fav}>
                          <Image src={Favorite} priority />
                          {/* <img src="/assets/Troffen - MVP/Fav.svg" alt="an image" /> */}
                        </div>
                      </div>
                      <div className={styles.subjek_content_tutor}>
                        <nav>John Doe</nav>
                        <Image src={Verify} priority />
                        {/* <img src="/assets/Troffen - MVP/Verify.svg" alt="an image" /> */}
                      </div>
                      <div className={styles.subjek_content_rating}>
                        <nav className={styles.star}>
                          <Image src={Star} priority className={styles.star} />
                          {/* <img src="/assets/Troffen - MVP/Star.svg" alt="an image" className={styles.star} /> */}
                        </nav>
                        <nav className={styles.ulasan}>4.5 (5 Ulasan)</nav>
                        <nav className={styles.divider}>
                          <Image src={Divider} priority />
                          {/* <img src="/assets/Troffen - MVP/Line 8.svg" alt="an image" /> */}
                        </nav>
                        <nav className={styles.group_of_reviewer}>
                          <Image src={GOR} priority />
                          {/* <img src="/assets/Troffen - MVP/Group of reviewer.svg" alt="an image" /> */}
                        </nav>
                        <nav className={styles.murid}>30 Murid</nav>
                      </div>
                      <hr />
                    </div>
                    <div className={styles.subjek_action}>
                      <div className={styles.subjek_action_harga}>Rp 100.000/jam</div>
                      <div className={styles.subjek_action_action}>
                        <button className={styles.button_submit}>BOOK</button>
                      </div>
                    </div>
                  </div>
                  <div className={styles.subjek_gallery_card}>
                    <div className={styles.subjek_thumbnail}>
                      <Image src={SubjekThumbnail} priority />
                      {/* <img src="/assets/Troffen - MVP/subjek-thumbnail.svg" alt="an image" /> */}
                    </div>
                    <div className={styles.subjek_content}>
                      <div className={styles.subjek_content_title}>
                        <div className={styles.subjek_content_title_main}>Basic UI/UX Design</div>
                        <div className={styles.subjek_content_title_fav}>
                          <Image src={Favorite} priority />
                          {/* <img src="/assets/Troffen - MVP/Fav.svg" alt="an image" /> */}
                        </div>
                      </div>
                      <div className={styles.subjek_content_tutor}>
                        <nav>John Doe</nav>
                        <Image src={Verify} priority />
                        {/* <img src="/assets/Troffen - MVP/Verify.svg" alt="an image" /> */}
                      </div>
                      <div className={styles.subjek_content_rating}>
                        <nav className={styles.star}>
                          <Image src={Star} priority className={styles.star} />
                          {/* <img src="/assets/Troffen - MVP/Star.svg" alt="an image" className={styles.star} /> */}
                        </nav>
                        <nav className={styles.ulasan}>4.5 (5 Ulasan)</nav>
                        <nav className={styles.divider}>
                          <Image src={Divider} priority />
                          {/* <img src="/assets/Troffen - MVP/Line 8.svg" alt="an image" /> */}
                        </nav>
                        <nav className={styles.group_of_reviewer}>
                          <Image src={GOR} priority />
                          {/* <img src="/assets/Troffen - MVP/Group of reviewer.svg" alt="an image" /> */}
                        </nav>
                        <nav className={styles.murid}>30 Murid</nav>
                      </div>
                      <hr />
                    </div>
                    <div className={styles.subjek_action}>
                      <div className={styles.subjek_action_harga}>Rp 100.000/jam</div>
                      <div className={styles.subjek_action_action}>
                        <button className={styles.button_submit}>BOOK</button>
                      </div>
                    </div>
                  </div>
                  <div className={styles.subjek_gallery_card}>
                    <div className={styles.subjek_thumbnail}>
                      <Image src={SubjekThumbnail} priority />
                      {/* <img src="/assets/Troffen - MVP/subjek-thumbnail.svg" alt="an image" /> */}
                    </div>
                    <div className={styles.subjek_content}>
                      <div className={styles.subjek_content_title}>
                        <div className={styles.subjek_content_title_main}>Basic UI/UX Design</div>
                        <div className={styles.subjek_content_title_fav}>
                          <Image src={Favorite} priority />
                          {/* <img src="/assets/Troffen - MVP/Fav.svg" alt="an image" /> */}
                        </div>
                      </div>
                      <div className={styles.subjek_content_tutor}>
                        <nav>John Doe</nav>
                        <Image src={Verify} priority />
                        {/* <img src="/assets/Troffen - MVP/Verify.svg" alt="an image" /> */}
                      </div>
                      <div className={styles.subjek_content_rating}>
                        <nav className={styles.star}>
                          <Image src={Star} priority className={styles.star} />
                          {/* <img src="/assets/Troffen - MVP/Star.svg" alt="an image" className={styles.star} /> */}
                        </nav>
                        <nav className={styles.ulasan}>4.5 (5 Ulasan)</nav>
                        <nav className={styles.divider}>
                          <Image src={Divider} priority />
                          {/* <img src="/assets/Troffen - MVP/Line 8.svg" alt="an image" /> */}
                        </nav>
                        <nav className={styles.group_of_reviewer}>
                          <Image src={GOR} priority />
                          {/* <img src="/assets/Troffen - MVP/Group of reviewer.svg" alt="an image" /> */}
                        </nav>
                        <nav className={styles.murid}>30 Murid</nav>
                      </div>
                      <hr />
                    </div>
                    <div className={styles.subjek_action}>
                      <div className={styles.subjek_action_harga}>Rp 100.000/jam</div>
                      <div className={styles.subjek_action_action}>
                        <button className={styles.button_submit}>BOOK</button>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
            <div className={styles.subjek_lihat_semua}>
              <button className={styles.button_lihat_semua}>Lihat Semua</button>
            </div>
          </div>
        </div>
      </section>

      <section id="benefit-sebagai">
        <div className={styles.container}>
          <div className={styles.benefit_sebagai}>
            <div className={styles.benefit_sebagai_tutor}>
              <Image src={GuruBenefit} priority />
            </div>
            <div className={styles.benefit_sebagai_student}>
              <Image src={MuridBenefit} />
            </div>
          </div>
        </div>
      </section>

      <Footer />

      {/* <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="an imageVercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </>
  );
}
